### Frontmatter tests ###
frontmatter_mandatory_fields:  ["title", "banner", "creation_date", "abstract", "template"]
frontmatter_mandatory_fields_by_templates:
  publication: ["conference_name"]

frontmatter_fields_value:
  category: ["cat1", "cat2"]