
##########################
# CollectionProcessor
# Plugins that process each collection after posts are parsed
##########################\###
CollectionProcessor:
  compute_full_collection_url:
    enable: true
  jsonld_collection:
    enable: false
  sort_collection:
    enable: false

##########################
# PostProcessor
# Plugins that process each post after they are parsed
##########################\###
PostProcessor:
  compute_full_post_url:
    enable: true
  jsonld:
    enable: false
  post_linter:
    check_content: false
    config_file: config/linter_config.yaml
    enable: false
    online_checks: false
  read_time:
    enable: false
    wpm: 260

##########################
# SitePreparsing
# Site wide plugins that execute before the parsing start.
##########################\###
SitePreparsing:
  copy_dir:
    enable: false
    targets:
    - assets/js > generated/static/js
    - assets/css > generated/static/css
    - assets/images > generated/static/images

##########################
# SiteProcessor
# Plugins that process the whole site once after parsing.
##########################\###
SiteProcessor:
  related_posts:
    enable: false
    num_related_posts: 6

##########################
# SiteRendering
# Plugins that render additional pages after the rendering.
##########################\###
SiteRendering:
  rss:
    enable: false
    template: rss.xml
  search:
    enable: false
    num_tfidf_keywords: 20
    output_path: static/js/
  sitemap:
    enable: true
    template: sitemap.xml
